version: '3'

volumes:
  cargo-registry:

services:
  validator:
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key &&
          sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -v \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    entrypoint: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8008

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    entrypoint: settings-tp -v -C tcp://validator:4004

  consensource-tp:
    image: target/consensource:client
    container_name: consensource-tp-test
    build:
      context: ../..
      dockerfile: ./processor/Dockerfile
    volumes:
      - cargo-registry:/root/.cargo/registry
    command: |
      bash -c "
        target/debug/cert-registry-processor -v -C tcp://validator:4004
      "

  test-runner:
    container_name: consensource-test-runner
    build:
      context: ../..
      dockerfile: ./integration_tests/processor/Dockerfile
    volumes:
      - ../..:/project/cert_registry
    command: |
      bash -c "
        python-protogen
        cd integration_tests/processor
        python3 -m nose2 -v processor_tests
      "
