[package]
name = "database"
version = "0.1.0"
authors = ["Target"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
r2d2 = { version = "0.8"}
r2d2-diesel = {version = "1.0.0"}
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
